# Generated by Django 4.2.5 on 2023-10-20 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("addressing", "0003_alter_province_latitude_alter_province_longitude"),
        ("biz", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EstimatedDate",
            new_name="EstablishedDate",
        ),
        migrations.AddField(
            model_name="branch",
            name="grand_open",
            field=models.DateField(blank=True, null=True, verbose_name="Grand open"),
        ),
        migrations.AddField(
            model_name="branch",
            name="local_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Local name"
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addressing.commune",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addressing.country",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addressing.district",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0.0,
                max_digits=9,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0.0,
                max_digits=9,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addressing.province",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addressing.village",
            ),
        ),
        migrations.AddField(
            model_name="branchaddress",
            name="zipcode",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Zipcode"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="business",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="code",
            field=models.CharField(blank=True, max_length=100, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Branch"),
        ),
        migrations.AlterField(
            model_name="branchaddress",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="business",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="business/logo"),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="biz.business",
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("zipcode", models.CharField(max_length=8, verbose_name="Zipcode")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressing.commune",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressing.country",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressing.district",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressing.province",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressing.village",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="media/business/branch"),
                ),
                ("alt", models.CharField(blank=True, max_length=150)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="biz.branch"
                    ),
                ),
            ],
        ),
    ]
