# Generated by Django 4.2.5 on 2023-10-03 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="address",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="logo",
        ),
        migrations.AddField(
            model_name="organization",
            name="is_permanent_closed",
            field=models.BooleanField(default=False, verbose_name="Permanent Closed"),
        ),
        migrations.AddField(
            model_name="organization",
            name="local_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Local name"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="slogan",
            field=models.CharField(blank=True, max_length=255, verbose_name="Slogan"),
        ),
        migrations.AddField(
            model_name="organization",
            name="slogan_local",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Slogan local"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="header_cover",
            field=models.ImageField(blank=True, upload_to="media/organizations/cover"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=100, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="OrganizationLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="media/organizations/logos"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("design_company", models.CharField(blank=True, max_length=150)),
                ("designer_name", models.CharField(blank=True, max_length=150)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
