# Generated by Django 4.2.5 on 2023-10-14 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ordering",
                    models.CharField(
                        blank=True,
                        choices=[
                            (" ", "Auto"),
                            ("ascend", "Ascending"),
                            ("descend", "Descending"),
                            ("order-1", "Order 1"),
                            ("order-2", "Order 2"),
                            ("order-3", "Order 3"),
                            ("order-4", "Order 4"),
                            ("order-5", "Order 5"),
                            ("order-6", "Order 6"),
                            ("order-7", "Order 7"),
                            ("order-8", "Order 8"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Ordering",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_tag", models.CharField(max_length=100, verbose_name="Alt tag")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="media/page/", verbose_name="Image"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web.page",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_image",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
