# Generated by Django 4.2.5 on 2023-09-17 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=35, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=25, verbose_name="email"),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="Primary phone"
                    ),
                ),
                (
                    "local_name",
                    models.CharField(
                        blank=True,
                        help_text="The name in your language",
                        max_length=50,
                        verbose_name="Local name",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Last name"
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "biography",
                    models.CharField(
                        blank=True,
                        help_text="Describe your self",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "recovery_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Recover Email",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                        default="Other",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("joined_on", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_set_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "email", "primary_phone")},
            },
        ),
        migrations.CreateModel(
            name="VerificationAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("id", "National Identity"),
                            ("other", "Other Identity"),
                        ],
                        default="passport",
                        max_length=150,
                        verbose_name="type",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="first_name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="last_name"),
                ),
                ("dob", models.DateField(verbose_name="date of birth")),
                (
                    "social_reference",
                    models.TextField(
                        blank=True,
                        help_text="provide link of your profiles for more reference information",
                        max_length=500,
                        verbose_name="social_reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reviewing", "Reviewing"),
                            ("rejected", "Rejected"),
                            ("verified", "Verified"),
                        ],
                        default="reviewing",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_account",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SettingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Timezone"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Language"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_dark",
                    models.BooleanField(default=False, verbose_name="Dark Mode"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserSettings",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActiveDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Device's Name"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Device's OS"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Browser"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Device's IP Address"
                    ),
                ),
                (
                    "lat",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Latitude"
                    ),
                ),
                (
                    "log",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Longitude"
                    ),
                ),
                (
                    "last_login_time",
                    models.DateTimeField(auto_now=True, verbose_name="Last Login Time"),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Login Time"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Access Token"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_device",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "is_avatar",
                    models.BooleanField(
                        default=False, unique=True, verbose_name="Is Avatar"
                    ),
                ),
                (
                    "is_cover_set",
                    models.BooleanField(default=False, verbose_name="Is cover"),
                ),
                (
                    "alt_image",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="alternative image image",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="user/images/account/",
                        verbose_name="image",
                    ),
                ),
                (
                    "uploaded_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Uploaded Date"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_gallery",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "AccountGallery",
                "verbose_name_plural": "AccountGalleries",
            },
        ),
    ]
