# Generated by Django 4.2.5 on 2023-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="primary_phone",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Primary phone"
            ),
        ),
    ]
