# Generated by Django 4.2.5 on 2023-10-13 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("addressing", "0003_country_flag"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(default=0.0, verbose_name="Latitude")),
                ("longitude", models.FloatField(default=0.0, verbose_name="Longitude")),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.URLField()),
                (
                    "custom_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/social_media_logos/"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="settinguser",
            name="is_dark",
        ),
        migrations.RemoveField(
            model_name="settinguser",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="accountgallery",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountgallery",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="activedevice",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activedevice",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="settinguser",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settinguser",
            name="date_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("%d-%m-%Y", "DD-MM-YYYY"),
                    ("%d-%m-%y", "DD-MM-YY"),
                    ("%a, %d %b %Y", "Mon, DD MMM YYYY"),
                    ("%A, %d %B %Y", "Mon, DD MMM YYYY"),
                    ("%B %d, %Y", "January DD, YYYY"),
                    ("%m-%d-%y", "MM-DD-YY"),
                    ("%m-%d-%Y", "MM-DD-YYYY"),
                    ("%y-%m-%d", "YY-MM-DD"),
                    ("%Y-%m-%d", "YYYY-MM-DD"),
                ],
                default="%d-%m-%Y",
                max_length=25,
                verbose_name="Date Format",
            ),
        ),
        migrations.AddField(
            model_name="settinguser",
            name="is_first_name",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="settinguser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Dark Mode"),
                    ("light", "Light Mode"),
                    ("auto", "System Mode"),
                ],
                default="auto",
                max_length=12,
                verbose_name="Theme Mode",
            ),
        ),
        migrations.AddField(
            model_name="settinguser",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="media/user/images/avatar/", verbose_name="Avatar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
        migrations.AlterField(
            model_name="accountgallery",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="media/user/images/account/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="settinguser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("km", "Khmer")],
                default="en",
                max_length=25,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="settinguser",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_UserSettings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                default="O",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="primary_phone",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Primary phone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_set_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="verificationaccount",
            name="dob",
            field=models.DateField(blank=True, verbose_name="date of birth"),
        ),
        migrations.CreateModel(
            name="UserSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "social_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.socialmedia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("home", "Home"), ("work", "Work")],
                        default=("home", "Home"),
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Address"
                    ),
                ),
                ("zip", models.PositiveBigIntegerField(blank=True, verbose_name="Zip")),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_city",
                        to="addressing.district",
                        verbose_name="City",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_commune",
                        to="addressing.commune",
                        verbose_name="Commune",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_country",
                        to="addressing.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_location",
                        to="accounts.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_province",
                        to="addressing.province",
                        verbose_name="State",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_village",
                        to="addressing.village",
                        verbose_name="Village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="AlternativePhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True, unique=True, verbose_name="Number"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_phone",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
