# Generated by Django 4.2.5 on 2023-10-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_location_rename_is_cover_accountgallery_is_cover_set_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
