# Generated by Django 4.2.5 on 2023-09-19 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0002_alter_user_primary_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountgallery",
            old_name="is_cover",
            new_name="is_cover_set",
        ),
        migrations.RenameField(
            model_name="settinguser",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="verificationaccount",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="activedevice",
            name="user",
        ),
        migrations.AddField(
            model_name="activedevice",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_device_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="auth.group", verbose_name="groups"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="verificationaccount",
            name="dob",
            field=models.DateField(blank=True, verbose_name="date of birth"),
        ),
    ]
