# Generated by Django 4.2.5 on 2023-10-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="log",
        ),
        migrations.AddField(
            model_name="location",
            name="lon",
            field=models.FloatField(default=0.0, verbose_name="Longitude"),
        ),
    ]
