# Generated by Django 4.2.5 on 2023-09-19 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_is_cover_accountgallery_is_cover_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activedevice",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_device",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
