# Generated by Django 4.2.5 on 2023-10-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_created_at_remove_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationaccount",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Superuser"),
        ),
    ]
