# Generated by Django 4.2.5 on 2023-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_activedevice_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                default="O",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
