# Generated by Django 4.2.5 on 2023-10-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_socialmedia_usersocial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
    ]
