# Generated by Django 4.2.5 on 2023-10-09 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternativePhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("home", "Home"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        default="mobile",
                        max_length=20,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(blank=True, verbose_name="Number"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_phone",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
