# Generated by Django 4.2.5 on 2023-10-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alternativephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativephone",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_phone",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
