# Generated by Django 4.2.5 on 2023-10-11 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settinguser",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="accountgallery",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountgallery",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="activedevice",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activedevice",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="alternativephone",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alternativephone",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="location",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="settinguser",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settinguser",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
        migrations.AddField(
            model_name="usersocial",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="submitted at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersocial",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="update at"),
        ),
    ]
