# Generated by Django 4.2.5 on 2023-10-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("addressing", "0003_country_flag"),
        ("accounts", "0012_remove_settinguser_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address_commune",
                to="addressing.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address_village",
                to="addressing.village",
                verbose_name="Village",
            ),
        ),
    ]
