# Generated by Django 4.2.5 on 2023-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="province",
            name="latitude",
            field=models.FloatField(default=0.0, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="province",
            name="longitude",
            field=models.FloatField(default=0.0, verbose_name="Longitude"),
        ),
    ]
