# Generated by Django 4.2.5 on 2023-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressing", "0002_remove_country_leader_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="flag",
            field=models.ImageField(
                blank=True, upload_to="media/country/images/flag/", verbose_name="Flag"
            ),
        ),
    ]
