# Generated by Django 4.2.5 on 2023-10-20 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("addressing", "0003_alter_province_latitude_alter_province_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, default=0.0, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, default=0.0, verbose_name="Longitude"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="countryleader",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="countryleader",
            name="phone",
            field=models.CharField(blank=True, max_length=100, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="countryleader",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
